version: "3.8"
services:
  websockify:
    build: ./websockify-master/docker
    ports:
      - "6800:6800"
    volumes: 
      - /home/vanek/remote/backend/config:/data
  buttonproxy:
    build: ./button_proxy
    ports: 
      - "8080:8080"
    volumes: 
      - /home/vanek/remote/backend/config:/config
  db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=remote
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
  # front: 
  #   build: ../frontend
  #   ports:
  #     - "5173:5173"
  #   volumes: 
  #     - /home/vanek/remote/frontend:/app


